description: >
  This is a sample executor using Docker and Node.
docker:
  - image: 'cimg/python:<<parameters.tag>>'
parameters:
  tag:
    default: "3.8"
    description: >
      Pick a specific image variant:
      https://hub.docker.com/r/cimg/python/tags
    type: string
